name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
    
    # Skip Ollama tests in CI
    - name: Run tests
      run: |
        pytest test_rag.py -v
    
    # Simple import check instead of running server
    - name: Check imports
      run: |
        python -c "from api import app; print('✅ API imports successfully')"